#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Baillard-style "geometry + stress" map (cf. results/baillard_geometry_stress_with_obs.pdf,
generated by the closest surviving analog scripts/baillard_kidiwela_model.py) but using
OUR DMODELS forward model (def_syn_6.xyzuvw, Okada dike + Yang spheroid via
axial_comb_V0.m/axial_dike_V0.m) instead of Baillard's simplified Kidiwela Mogi-sphere
parametrization, and OUR splitting-pipeline observations (get_station_obs_hemmett)
instead of Baillard's per-event gridded/binned observation field.

Draws, over grayscale bathymetry:
  - stations (6 production stations, AXID1 excluded)
  - feature/geometry lines for the syn-eruption source set (dike_syn_1,
    fault_pre_syn_2, fault_pre_syn_3 - the fault_coord_dic entries active for
    period='syn' in deformation_analysis.py/_hemmett.py) - in BLUE
  - tick marks (double-headed, undirected) showing the modelled principal
    (most compressive) stress direction from def_syn_6.xyzuvw's SIGMA1 field,
    subsampled over the DMODELS grid - in BLUE
  - tick marks showing our OBSERVED fast direction (syn-eruption, per station,
    from get_station_obs_hemmett) - in RED

Caveat: unlike baillard_kidiwela_model.py's densely gridded/binned per-event
observation field, we only have one representative (median) observed fast
direction per station (get_station_obs_hemmett gives no lat/lon-resolved event
positions) - so the red ticks are one per station, not a gridded field.

Output: deformation_figures/def_syn_6_geometry_stress_hemmett.pdf
"""

import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from PIL import Image as PILImage
import tifffile

import deformation_util as adutil
import GMT as ggmt
import projection as gproj

HERE = os.path.dirname(os.path.abspath(__file__))
disp_dir = os.path.join(HERE, '..', 'Axial_Deformation') + os.sep
output_dir = os.path.join(HERE, 'deformation_figures') + os.sep

STATION_LIST = ['AXCC1','AXEC1','AXEC2','AXEC3','AXAS1','AXAS2']  # no AXID1

ini_lon=-130.1
ini_lat=45.9
idz=0
poisson=0.25
mu_el=1

x_lim=[5,11]
y_lim=[1,8]

# Syn-eruption feature/geometry lines (period='syn' subset of fault_coord_dic
# in deformation_analysis.py / deformation_analysis_hemmett.py)
FAULT_COORD_SYN = {
    'dike_syn_1':     {'center':[8.2 ,5.2],'angle':89, 'length':[0,4]},
    'fault_pre_syn_2':{'center':[8.2 ,5.2],'angle':-62,'length':[0,1.5]},
    'fault_pre_syn_3':{'center':[8.75,3.79],'angle':118,'length':[0,1.5]},
}

# ── Load DMODELS syn_6 field and compute SIGMA1 ────────────────────────────────

print("Loading def_syn_6.xyzuvw and computing SIGMA1 field...")
(X,Y,Z,Ux,Uy,Uz) = adutil.read_disp_file(os.path.join(disp_dir,'def_syn_6.xyzuvw'), flag_plot=False)
X_slice=X[:,:,idz]; Y_slice=Y[:,:,idz]
Ux_slice=Ux[:,:,idz]; Uy_slice=Uy[:,:,idz]

SIGMA1 = adutil.compute_sigma1_2d(X_slice,Y_slice,Ux_slice,Uy_slice,poisson,mu_el)

# ── Vectorized azimuth-of-compression field (deg, trigo->az, same convention
#    as plot_sigma1_stations' per-station extraction) ──────────────────────────

Vx = SIGMA1[:,:,0]
Vy = SIGMA1[:,:,1]
phi_cal = np.degrees(np.arctan2(Vy, Vx))
phi_cal = np.where(phi_cal>=90, phi_cal-180, phi_cal)
phi_cal = np.where(phi_cal<=-90, phi_cal+180, phi_cal)
az_cal = (-phi_cal+90) % 360   # gproj.trigo2az, vectorized

# ── Model tick-mark grid (subsample the native ~0.05 km DMODELS grid) ─────────

STEP = 6  # ~0.3 km spacing at 0.05 km native resolution
Xq = X_slice[::STEP,::STEP]
Yq = Y_slice[::STEP,::STEP]
Aq = az_cal[::STEP,::STEP]
r = np.radians(Aq)
Uq = np.sin(r); Vq = np.cos(r)

# ── Observed fast direction per station (syn-eruption) ─────────────────────────

print("Loading observed splitting-pipeline results (syn-eruption)...")
obs_syn = adutil.get_station_obs_hemmett(period='syn')

station_dic = ggmt.read_stationfile()

# ── Bathymetry ──────────────────────────────────────────────────────────────────

print("Loading bathymetry...")
KM_PER_DEG_LAT = 111.32
KM_PER_DEG_LON = 111.32*np.cos(np.radians(ini_lat))
BATHY = ('/Users/mhemmett/Downloads/MGDS_Download/AxialSeamount_MBARI/'
         'AxialSummit_MAUV_10Mar2021_All_OverEM302_Topo1m_histEq11.tif')
have_bathy = os.path.exists(BATHY)
if have_bathy:
    PILImage.MAX_IMAGE_PIXELS=None
    _p=PILImage.open(BATHY); _t=_p.tag_v2
    _olon,_olat=_t[33922][3],_t[33922][4]; _pl,_pb=_t[33550][0],_t[33550][1]
    _nc,_nr=_p.size; _p.close()
    _c0=max(0,int(((ini_lon+x_lim[0]/KM_PER_DEG_LON)-_olon)/_pl)-2)
    _c1=min(_nc,int(((ini_lon+x_lim[1]/KM_PER_DEG_LON)-_olon)/_pl)+2)
    _r0=max(0,int((_olat-(ini_lat+y_lim[1]/KM_PER_DEG_LAT))/_pb)-2)
    _r1=min(_nr,int((_olat-(ini_lat+y_lim[0]/KM_PER_DEG_LAT))/_pb)+2)
    _rgb=tifffile.imread(BATHY)[_r0:_r1,_c0:_c1]
    _ds=max(1,max(_rgb.shape[:2])//1024); _rgb=_rgb[::_ds,::_ds]
    _gray=np.dot(_rgb[...,:3].astype(np.float32),[0.299,0.587,0.114]).astype(np.uint8)
    _ext=[(_olon+_c0*_pl-ini_lon)*KM_PER_DEG_LON,(_olon+_c1*_pl-ini_lon)*KM_PER_DEG_LON,
          (_olat-_r1*_pb-ini_lat)*KM_PER_DEG_LAT,(_olat-_r0*_pb-ini_lat)*KM_PER_DEG_LAT]
else:
    print(f"  WARNING: bathymetry file not found at {BATHY} - skipping background")

# ── Plot ──────────────────────────────────────────────────────────────────────

fig, ax = plt.subplots(figsize=[7,6])

if have_bathy:
    ax.imshow(_gray, origin='upper', extent=_ext, aspect='auto', cmap='gray', alpha=0.8, zorder=0)

### Model principal-stress tick marks (blue, double-headed = undirected axis)
qkw = dict(scale=18, width=0.0035, headlength=0, headaxislength=0, headwidth=0,
           pivot='middle', color='blue', alpha=0.7, zorder=3)
ax.quiver(Xq, Yq,  Uq,  Vq, **qkw)
ax.quiver(Xq, Yq, -Uq, -Vq, **qkw)

### Feature/geometry lines (syn-eruption dike/fault set) - blue
for key, feat in FAULT_COORD_SYN.items():
    ggmt.plot_box(feat['center'], feat['angle'], feat['length'], width_prof=None,
                  ax=ax, flag_label=False, key=key, flag_plot=True, fontsize=12,
                  color='blue', ls='-', lw=1.8, flag_cross=False)

### Observed fast direction (red, one tick per station)
obs_qkw = dict(scale=18, width=0.005, headlength=0, headaxislength=0, headwidth=0,
               pivot='middle', color='red', alpha=0.95, zorder=7)
for sta in STATION_LIST:
    lon,lat = station_dic[sta]['lon'], station_dic[sta]['lat']
    x_sta,y_sta = gproj.ll2xy(lon,lat,ini_lon,ini_lat)
    fast_obs = obs_syn[sta]['fast']
    if fast_obs is None:
        continue
    ro = np.radians(fast_obs)
    uo, vo = np.sin(ro), np.cos(ro)
    ax.quiver(x_sta, y_sta,  uo,  vo, **obs_qkw)
    ax.quiver(x_sta, y_sta, -uo, -vo, **obs_qkw)

### Stations
for sta in STATION_LIST:
    lon,lat = station_dic[sta]['lon'], station_dic[sta]['lat']
    x_sta,y_sta = gproj.ll2xy(lon,lat,ini_lon,ini_lat)
    ax.plot(x_sta, y_sta, '^', ms=9, mfc='yellow', mec='black', mew=1.0, zorder=12)
    ax.text(x_sta+0.12, y_sta+0.12, sta, fontsize=7.5, fontweight='bold', zorder=13)

### Cosmetic
ax.set_aspect('equal')
ax.set_xlim(x_lim); ax.set_ylim(y_lim)
ax.set_xlabel('X [km]'); ax.set_ylabel('Y [km]')
ax.set_title('def_syn_6: modelled principal stress direction vs. observed $\\phi$')

legend_elements=[
    mlines.Line2D([0],[0],color='blue',lw=1.8,label='Model $\\sigma_1$ (compression) / dike-fault geometry'),
    mlines.Line2D([0],[0],color='red',lw=2.0,label='Observed $\\phi$ (syn-eruption, per station)'),
]
ax.legend(handles=legend_elements, fontsize=8, loc='lower right', framealpha=0.95)

if not os.path.exists(output_dir):
    os.makedirs(output_dir)
name_pdf = output_dir + 'def_syn_6_geometry_stress_hemmett.pdf'
fig.savefig(name_pdf, format='pdf', dpi=300, bbox_inches='tight')
print(f"\nSaved {name_pdf}")
